package ru.murad.myvpn.dto;
public enum PaymentVerificationOutcome { STILL_PENDING, SUCCEEDED, ALREADY_SUCCEEDED,
    CANCELED, ALREADY_CANCELED, TOO_EARLY, CHECKOUT_INCOMPLETE,
    MANUAL_REVIEW_REQUIRED, PROVIDER_UNAVAILABLE, PROVIDER_RESULT_UNCERTAIN, NOT_FOUND,
    TERMINAL, AMBIGUOUS_PAYMENT_STATE }
