package ru.murad.myvpn.exception;

public enum VpnProviderFailureCode {
    PERMANENT,
    AUTHENTICATION_FAILED,
    RATE_LIMITED,
    PROVIDER_UNAVAILABLE,
    REQUEST_TIMEOUT,
    CLIENT_NOT_FOUND,
    CLIENT_CONFLICT,
    INVALID_PROVIDER_RESPONSE,
    UNSUPPORTED_INBOUND_CONFIGURATION,
    MUTATION_RECONCILIATION_FAILED,
    REQUEST_BUDGET_EXHAUSTED,
    UNKNOWN_PROVIDER_ERROR
}
