package ru.murad.myvpn.model;

public enum VpnDeliveryFailureCode {
    RELATIONSHIP_MISMATCH,
    TELEGRAM_RATE_LIMITED,
    TELEGRAM_UNAVAILABLE,
    TELEGRAM_BOT_BLOCKED,
    TELEGRAM_CHAT_NOT_FOUND,
    TELEGRAM_MESSAGE_TOO_LONG,
    TELEGRAM_REJECTED,
    TELEGRAM_GATEWAY_UNEXPECTED,
    SNAPSHOT_INVALID,
    MAX_ATTEMPTS_REACHED
}
