spring:
  application:
    name: myvpn
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

telegram:
  admin-ids: ${TELEGRAM_ADMIN_IDS:}

vpn:
  lifecycle:
    expiration-check-delay: 60000
    configuration-cleanup-delay: 3600000
