package ru.murad.myvpn.service;

public enum PaymentActivationFailureCode {
    VPN_PROVIDER_TRANSIENT,
    VPN_PROVIDER_PERMANENT,
    ACTIVATION_PROVIDER_UNEXPECTED,
    ACTIVATION_PROVIDER_RESULT_MISMATCH,
    VPN_PROVIDER_RESULT_INVALID,
    ACTIVATION_MAX_ATTEMPTS_REACHED,
    ACTIVATION_SNAPSHOT_INVALID
}
