package com.myvpn.android.ui
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.myvpn.android.data.VpnAccessResponse
import com.myvpn.android.data.VpnAccessSource
import com.myvpn.android.vpn.VpnEngine
import com.myvpn.android.vpn.VpnConnectionState
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*
sealed interface MainUiState{data object Initializing:MainUiState;data object Registering:MainUiState;data class Provisioning(val entitlement:String):MainUiState;data class Ready(val access:VpnAccessResponse,val message:String?=null):MainUiState;data object AwaitingPermission:MainUiState;data object Connecting:MainUiState;data object Connected:MainUiState;data object Disconnecting:MainUiState;data object RetryRequired:MainUiState;data class Error(val message:String):MainUiState}
class MainViewModel(private val repo: VpnAccessSource, private val engine: VpnEngine):ViewModel(){private val _state=MutableStateFlow<MainUiState>(MainUiState.Initializing);val state=_state.asStateFlow();private var config:String?=null;private var ready:VpnAccessResponse?=null;init{reload();viewModelScope.launch{engine.state.collect{when(it){VpnConnectionState.Connected->_state.value=MainUiState.Connected;VpnConnectionState.Connecting->_state.value=MainUiState.Connecting;VpnConnectionState.Disconnecting->_state.value=MainUiState.Disconnecting;is VpnConnectionState.Failed->_state.value=ready?.let{r->MainUiState.Ready(r,it.message)}?:MainUiState.Error(it.message);VpnConnectionState.Disconnected->ready?.let{_state.value=MainUiState.Ready(it)};VpnConnectionState.PermissionDenied->ready?.let{r->MainUiState.Ready(r,"VPN permission was denied")}}}}};fun reload(){viewModelScope.launch{runCatching{_state.value=MainUiState.Registering;repeat(6){val a=repo.current();when(a.status){"READY"->{config=a.configuration;ready=a;_state.value=MainUiState.Ready(a);return@launch};"RETRY_REQUIRED"->{_state.value=MainUiState.RetryRequired;return@launch};else->_state.value=MainUiState.Provisioning(a.entitlement)};delay(if(it<2)2000 else 5000)}}.onFailure{_state.value=MainUiState.Error("Network or authentication error")}}};fun connect(){if(config!=null)_state.value=MainUiState.AwaitingPermission};fun onPermissionResult(granted:Boolean){val c=config;val r=ready;if(!granted){if(r!=null)_state.value=MainUiState.Ready(r,"VPN permission was denied");return};if(c!=null)viewModelScope.launch{_state.value=MainUiState.Connecting;runCatching{engine.start(c)}.onFailure{_state.value=MainUiState.Ready(r?:return@onFailure,"VPN connection could not be started")}}};fun disconnect(){viewModelScope.launch{_state.value=MainUiState.Disconnecting;engine.stop()}}}
