package ru.murad.myvpn.service.impl;
import java.net.URI;import java.time.*;import java.util.UUID;
import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import ru.murad.myvpn.dto.*;import ru.murad.myvpn.exception.*;import ru.murad.myvpn.model.*;import ru.murad.myvpn.repository.*;import ru.murad.myvpn.service.*;
@Service @RequiredArgsConstructor public class PaymentCheckoutTransactionServiceImpl implements PaymentCheckoutTransactionService {
 private final VpnTariffRepository tariffs;private final PaymentOrderRepository orders;private final PaymentOrderCreationService creation;private final CreatedPaymentValidator validator;
 @Transactional public PreparedCheckout prepareCheckout(UUID accountId,String code,PaymentProviderType provider,Duration ttl,Instant now){var tariff=tariffs.findByCodeAndActiveTrue(code).orElseThrow(()->new VpnTariffNotFoundException(code));var order=orders.findOpenByAccount(accountId).orElse(null);if(order!=null&&!order.getTariff().getId().equals(tariff.getId()))throw new OpenPaymentOrderDifferentTariffException();if(order!=null&&!order.getExpiresAt().isAfter(now)){order.markExpired(now);orders.saveAndFlush(order);order=null;}if(order==null)order=creation.create(accountId,code,provider,ttl);if(order.getProvider()!=provider)throw new OpenPaymentOrderAlreadyExistsException();if(order.getStatus()==PaymentStatus.NEW){order.markCreating(now);orders.saveAndFlush(order);}return prepared(order);}
 @Transactional public PaymentCheckoutResult applyCreatedPayment(PreparedCheckout p,CreatedPayment c,Instant now){var o=orders.findByIdForUpdate(p.orderId()).orElseThrow(PaymentNotFoundException::new);valid(o,p);validator.validate(o.getProvider(),c,now);o.markPending(c.providerPaymentId(),c.confirmationUrl().toString(),c.providerCreatedAt(),c.expiresAt(),now);orders.saveAndFlush(o);return result(o);}
 @Transactional public void markPermanentFailure(PreparedCheckout p,Instant now){var o=orders.findByIdForUpdate(p.orderId()).orElseThrow(PaymentNotFoundException::new);valid(o,p);if(o.getStatus()==PaymentStatus.CREATING){o.markFailed("PROVIDER_REJECTED",now);orders.saveAndFlush(o);}}
 private void valid(PaymentOrder o,PreparedCheckout p){if(!o.getAccount().getId().equals(p.accountId())||!o.getIdempotenceKey().equals(p.idempotenceKey()))throw new PaymentProviderUncertainException("Payment order changed concurrently");}
 private PreparedCheckout prepared(PaymentOrder o){URI u=o.getConfirmationUrl()==null?null:URI.create(o.getConfirmationUrl());return new PreparedCheckout(o.getId(),o.getAccount().getId(),o.getTariff().getId(),o.getProvider(),o.getIdempotenceKey(),o.getAmount(),o.getCurrency(),o.getTariffCodeSnapshot(),o.getTariffNameSnapshot(),o.getDurationDaysSnapshot(),o.getStatus(),u,o.getExpiresAt());}
 private PaymentCheckoutResult result(PaymentOrder o){return new PaymentCheckoutResult(o.getId(),o.getTariffNameSnapshot(),o.getAmount(),o.getCurrency(),o.getDurationDaysSnapshot(),o.getStatus(),new CheckoutDestination.RedirectUrl(URI.create(o.getConfirmationUrl())),o.getExpiresAt());}
}
